name: Release Docker Image and Update K8s Deployment

on:
  release:
    types: [published] # This workflow runs when a new release is published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v4 # Checkout the repository containing your application code and Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Set up Docker Buildx for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Log in to Docker Hub using provided credentials
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_TOKEN }} # Your Docker Hub Personal Access Token

      - name: Extract Release Tag
        id: get_tag # Assign an ID to this step to reference its outputs
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT # Extract the tag name from GITHUB_REF

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5 # Build and push the Docker image
        with:
          context: . # Build context is the current directory (application repo)
          push: true # Push the image to Docker Hub
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ncas-general-cdl-creator-frontent:${{ steps.get_tag.outputs.RELEASE_TAG }} # Tag with release name
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max
